/* Curated release history. Dates refer to the event described, not training cutoffs.
 * Primary sources establish releases; explicitly labeled reports resolve date gaps.
 * See README.md for date conventions, leaderboard discovery, and scope.
 * A classic script keeps the complete site usable from file://, without a server.
 */
window.MODEL_ATLAS = (() => {
  const companies = [
    { id: 'openai', name: 'OpenAI', aliases: 'GPT ChatGPT o1 o3', color: '#4e755c' },
    { id: 'google', name: 'Google', aliases: 'Google DeepMind 谷歌 Gemini Gemma BERT PaLM', color: '#587db0' },
    { id: 'anthropic', name: 'Anthropic', aliases: 'Claude 克劳德', color: '#b47d60' },
    { id: 'meta', name: 'Meta', aliases: 'Facebook Llama Muse Spark', color: '#647faf' },
    { id: 'deepseek', name: 'DeepSeek', aliases: '深度求索 深求', color: '#567fa9' },
    { id: 'qwen', name: '阿里巴巴', aliases: 'Alibaba Qwen 阿里巴巴 阿里云 通义 千问 通义千问', color: '#8c76ae' },
    { id: 'mistral', name: 'Mistral', aliases: 'Mistral AI Mixtral', color: '#bd8a46' },
    { id: 'xai', name: 'xAI', aliases: 'Grok SpaceXAI', color: '#64685f' },
    { id: 'moonshot', name: '月之暗面', aliases: 'Moonshot AI Kimi', color: '#73759e' },
    { id: 'zhipu', name: '智谱', aliases: '智谱华章 Zhipu Z.ai GLM ChatGLM', color: '#548d89' },
    { id: 'minimax', name: 'MiniMax', aliases: '稀宇科技 海螺 M1 M2 M3', color: '#847891' },
    { id: 'xiaomi', name: '小米', aliases: 'Xiaomi MiMo 小米大模型', color: '#b38462' },
    { id: 'stepfun', name: '阶跃星辰', aliases: 'StepFun Step 阶跃', color: '#688399' },
    { id: 'microsoft', name: 'Microsoft', aliases: '微软 Phi', color: '#65889a' },
    { id: 'amazon', name: 'Amazon', aliases: '亚马逊 AWS Nova', color: '#9f8963' },
    { id: 'nvidia', name: 'NVIDIA', aliases: '英伟达 Nemotron', color: '#7e9063' },
    { id: 'tencent', name: '腾讯', aliases: 'Tencent 混元 Hunyuan Hy3 Hy4 T1', color: '#678998' },
    { id: 'bytedance', name: '字节跳动', aliases: 'ByteDance Seed 字节跳动 豆包 Doubao Dola', color: '#748e92' },
  ];
  // Highest listed score per organization in the AA "Current" leaderboard.
  // Entry order preserves the source's order when displayed scores are tied.
  const companyRanking = {
    checkedAt: '2026-10-01',
    source: 'https://artificialanalysis.ai/leaderboards/models',
    methodology: 'https://artificialanalysis.ai/methodology/intelligence-benchmarking',
    metric: 'Artificial Analysis Intelligence Index',
    version: '4.3.2',
    selection: 'highest-listed-score',
    entries: [
  {
    "company": "anthropic",
    "model": "Claude Opus 5.5 (max with fallback)",
    "score": 58
  },
  {
    "company": "openai",
    "model": "GPT-6 Astra (max)",
    "score": 53
  },
  {
    "company": "google",
    "model": "Gemini 4 Argon (high)",
    "score": 53
  },
  {
    "company": "meta",
    "model": "Muse Spark 1.3 (max)",
    "score": 48
  },
  {
    "company": "xai",
    "model": "Grok 4.7 (xhigh)",
    "score": 46
  },
  {
    "company": "xiaomi",
    "model": "MiMo-V2.6-Pro",
    "score": 46
  },
  {
    "company": "qwen",
    "model": "Qwen3.8 Max (0902)",
    "score": 45
  },
  {
    "company": "zhipu",
    "model": "GLM-5.3 (max)",
    "score": 45
  },
  {
    "company": "stepfun",
    "model": "Step 5 Preview",
    "score": 44
  },
  {
    "company": "moonshot",
    "model": "Kimi K3 (max)",
    "score": 44
  },
  {
    "company": "deepseek",
    "model": "DeepSeek V4.1 Flash (max)",
    "score": 39
  },
  {
    "company": "minimax",
    "model": "MiniMax-M3",
    "score": 29
  },
  {
    "company": "tencent",
    "model": "Hy3",
    "score": 25
  },
  {
    "company": "nvidia",
    "model": "Nemotron 3 Ultra",
    "score": 23
  },
  {
    "company": "bytedance",
    "model": "Doubao Seed Code",
    "score": 17,
    "estimated": true
  },
  {
    "company": "mistral",
    "model": "Mistral Medium 3.5",
    "score": 14
  },
  {
    "company": "amazon",
    "model": "Nova 2.0 Pro Preview (medium)",
    "score": 14,
    "estimated": true
  },
  {
    "company": "microsoft",
    "model": "Phi-4 Mini",
    "score": 6,
    "estimated": true
  }
],
  };
  const kinds = { paper: '论文公开', release: '模型发布', preview: '预览发布', product: '产品上线', weights: '权重开放', announcement: '官方公告' };
  const themes = {
    '2017': 'Transformer 架构',
    '2018': '预训练研究', '2019': '规模与迁移学习', '2020': '少样本学习',
    '2021': '代码模型', '2022': '指令对齐与对话产品', '2023': '主流模型系列',
    '2024': '多模态、开放权重与推理', '2025': '推理模型与工具调用', '2026': '多模态与智能体',
  };
  const source = (title, url) => ({ title, url });
  const oa = slug => source('OpenAI · 官方发布', `https://openai.com/index/${slug}/`);
  const an = slug => source('Anthropic · 官方发布', `https://www.anthropic.com/news/${slug}`);
  const ds = slug => source('DeepSeek · 官方发布日志', `https://api-docs.deepseek.com/news/${slug}/`);
  const qw = slug => source('Qwen · 官方博客', `https://qwenlm.github.io/blog/${slug}/`);
  const paper = id => source('原始论文 · arXiv', `https://arxiv.org/abs/${id}`);
  function event(id, date, name, company, kind, summary, tags, sources, milestone = false, details = '', dateNote = '') {
    return { id, date, name, company, kind, summary, tags, sources: Array.isArray(sources) ? sources : [sources], milestone, details, dateNote };
  }
  const releases = [
    event('transformer', '2017-06-12', 'Transformer', 'google', 'paper',
      'Google 团队在《Attention Is All You Need》中提出 Transformer，以注意力机制构建序列模型。', ['模型架构', '注意力机制'],
      [paper('1706.03762'), source('Google Research · 论文页面', 'https://research.google/pubs/attention-is-all-you-need/')], true,
      '论文提出基于注意力机制的编码器—解码器架构，使用多头注意力与位置编码，在机器翻译任务中验证效果。这一研究为后来的 GPT、BERT 等预训练模型提供了架构基础。',
      '采用 arXiv 第一版于 2017 年 6 月 12 日公开的日期；此节点记录基础架构论文，不是聊天产品或后续大模型的发布。'),
    event('gpt-1', '2018-06-11', 'GPT-1', 'openai', 'paper',
      '将无监督语言预训练与任务微调结合，研究预训练模型的跨任务迁移。', ['预训练', '文本'], oa('language-unsupervised'), true,
      'OpenAI 将 Transformer 与无监督预训练结合：先从无标注文本中学习，再对具体任务进行微调。最初的研究名为 GPT，后来通常被称为 GPT-1。', '记录论文与研究公告公开的日期，不是聊天产品上线日期。'),
    event('bert', '2018-10-11', 'BERT', 'google', 'paper',
      '通过双向上下文学习语言表示，推动预训练模型在阅读理解等任务中的应用。', ['双向编码', '语言理解'], paper('1810.04805'), false,
      'BERT 是编码器模型，代表与 GPT 不同的技术路线。这里将它作为理解预训练发展脉络的研究节点收录。', '使用 arXiv 第一版提交日期；不是后续代码发布或论文修订日期。'),
    event('gpt-2', '2019-02-14', 'GPT-2', 'openai', 'release',
      '更大规模的语言模型展现出连贯文本生成与零样本任务能力。', ['文本生成', '零样本'], oa('better-language-models'), true,
      'GPT-2 采用分阶段发布策略。此次公告介绍模型并开放较小版本；最大的 1.5B 版本权重于同年 11 月 5 日开放。', '记录首次公告与阶段性发布，非完整权重开放日。'),
    event('t5', '2019-10-23', 'T5', 'google', 'paper',
      '将不同语言任务统一成「文本到文本」，探索迁移学习的共同框架。', ['Text-to-Text', '迁移学习'], paper('1910.10683'), false,
      '分类、翻译、摘要与问答都可以用输入文本、输出文本来表达。这种统一形式让不同任务得以在同一模型框架下研究。', '使用 arXiv 第一版提交日期。'),
    event('gpt-3', '2020-05-28', 'GPT-3', 'openai', 'paper',
      '1750 亿参数与少样本学习，让模型通过提示中的少量示例完成多种任务。', ['规模化', '少样本学习'], paper('2005.14165'), true,
      '论文研究了在不更新模型参数的情况下，通过上下文中的任务描述和示例完成任务的能力。参数规模的提升使通用语言模型进入新的阶段。', '记录论文首次公开；API 测试版于 2020 年 6 月另行推出。'),
    event('codex', '2021-08-10', 'Codex', 'openai', 'preview',
      '把自然语言转化为代码，语言模型开始成为开发者的编程助手。', ['代码生成', '自然语言编程'], oa('openai-codex'), true,
      '这一代 Codex 是基于 GPT-3 的代码模型，支持将自然语言指令转成程序，并以私有 API 测试版形式提供。', '这里指 2021 年的 Codex 模型，与 2025 年推出的同名编程智能体产品区分。'),
    event('instructgpt', '2022-01-27', 'InstructGPT', 'openai', 'release',
      '引入人类反馈强化学习，让语言模型更好地遵循用户意图。', ['RLHF', '指令遵循'], oa('instruction-following'), true,
      '结合人类示范、偏好比较和强化学习，研究从「预测下一个词」走向「按用户要求完成任务」的对齐方法。'),
    event('palm', '2022-04-04', 'PaLM', 'google', 'announcement',
      'Google 展示大规模 Pathways 语言模型，研究规模扩展下的推理与语言能力。', ['规模化', '推理'],
      source('Google Research · PaLM 研究公告', 'https://research.google/blog/pathways-language-model-palm-scaling-to-540-billion-parameters-for-breakthrough-performance/'), false,
      'PaLM 以 5400 亿参数展示语言、代码与推理任务上的研究进展。这是研究公告，不代表模型当时已向公众开放使用。'),
    event('chatgpt', '2022-11-30', 'ChatGPT', 'openai', 'product',
      '基于 GPT-3.5 系列的对话产品开放研究预览，支持多轮问答。', ['对话', 'GPT-3.5'], oa('chatgpt'), true,
      '通过多轮对话，用户可以追问、要求修改，或让模型解释回答。这个节点记录的是 ChatGPT 的产品上线，而不是一个独立基础模型的发布。'),
    event('llama-1', '2023-02-24', 'LLaMA', 'meta', 'announcement',
      'Meta 发布基础语言模型研究，向研究社区提供申请访问的模型权重。', ['基础模型', '研究访问'],
      source('Meta AI · LLaMA 官方公告', 'https://ai.meta.com/blog/large-language-model-llama-meta-ai/'), true,
      '第一代 LLaMA 包括多个参数规模，帮助研究者在更可控的计算条件下研究语言模型。', '初代权重采用申请式研究访问与非商业研究许可。'),
    event('claude-1', '2023-03-14', 'Claude', 'anthropic', 'release',
      'Anthropic 推出 Claude 与 Claude Instant，强调有帮助、诚实和安全的对话体验。', ['对话', '安全对齐'], an('introducing-claude'), true,
      '首批发布包含性能更强的 Claude 与更轻量的 Claude Instant，通过合作伙伴和 API 提供服务。'),
    event('gpt-4', '2023-03-14', 'GPT-4', 'openai', 'release',
      '改进文本任务表现，首次展示 GPT 系列的图像输入能力。', ['多模态', '复杂推理'], oa('gpt-4-research'), true,
      'GPT-4 支持文本和图像输入、文本输出。发布初期不同能力采用不同开放节奏，图像输入没有同时全面开放。'),
    event('claude-2', '2023-07-11', 'Claude 2', 'anthropic', 'release',
      '增强编程与推理，支持长文档处理，并推出面向公众的 claude.ai 测试版。', ['长上下文', '对话'], an('claude-2'), false,
      'Claude 2 与新的网站测试版同步推出。长上下文处理能力使整篇文档分析成为重要使用场景。'),
    event('llama-2', '2023-07-18', 'Llama 2', 'meta', 'weights',
      '开放预训练与对话模型权重，并在专用许可下支持研究和商业使用。', ['开放权重', '对话模型'],
      source('Meta · Llama 2 发布公告', 'https://about.fb.com/news/2023/07/llama-2/'), true,
      'Llama 2 提供基础模型和经过对话微调的版本，可用于研究和商业应用。', '开放权重不代表没有许可限制；具体使用条件以 Llama 2 许可为准。'),
    event('qwen-7b', '2023-08-03', 'Qwen-7B', 'qwen', 'weights',
      '开放 7B 基础与对话模型权重，支持中文和英文任务。', ['开放权重', '中英双语'],
      source('Qwen · 官方仓库发布日期表', 'https://github.com/QwenLM/Qwen'), true,
      '官方仓库提供模型权重，以及推理和微调示例。', '记录 Qwen-7B 权重开放日，不是通义千问品牌首次亮相日期。'),
    event('mistral-7b', '2023-09-27', 'Mistral 7B', 'mistral', 'weights',
      '高效的 7B 模型以 Apache 2.0 许可发布，展示小型模型的实用潜力。', ['开放权重', '高效模型'],
      source('Mistral AI · Mistral 7B', 'https://mistral.ai/news/announcing-mistral-7b/'), true,
      'Mistral 7B 采用分组查询注意力与滑动窗口注意力，减少推理时的内存使用。'),
    event('grok-1', '2023-11-03', 'Grok', 'xai', 'preview',
      'xAI 公布 Grok，结合 X 平台信息，向部分用户开放早期体验。', ['对话', '实时信息'],
      source('xAI · Announcing Grok', 'https://x.ai/news/grok'), false,
      '这一节点是产品与模型的早期公告，并非后来 Grok-1 基础模型权重开放的日期。', '采用官方公告所标注的 11 月 3 日。'),
    event('gemini-1', '2023-12-06', 'Gemini 1.0', 'google', 'release',
      'Google 推出原生多模态模型家族，以 Ultra、Pro、Nano 覆盖不同场景。', ['原生多模态', '模型家族'],
      source('Google · Introducing Gemini', 'https://blog.google/innovation-and-ai/technology/ai/google-gemini-ai/'), true,
      'Gemini 从训练阶段结合多种模态。不同型号分批开放，不能将全家族公告理解为所有型号当天均可使用。'),
    event('gemini-1-5', '2024-02-15', 'Gemini 1.5', 'google', 'preview',
      '长上下文成为焦点，Gemini 1.5 Pro 展示百万 token 级上下文处理。', ['长上下文', '多模态'],
      source('Google · Gemini 1.5 发布公告', 'https://blog.google/innovation-and-ai/products/google-gemini-next-generation-model-february-2024/'), true,
      '首次发布提供有限预览，展示对长文档、代码、音频和视频的理解能力。', '此日期为预览公告日，不是全面可用日期。'),
    event('claude-3', '2024-03-04', 'Claude 3', 'anthropic', 'release',
      'Opus、Sonnet、Haiku 组成新模型家族，并加入视觉理解能力。', ['视觉理解', '模型家族'], an('claude-3-family'), true,
      '三个型号分别面向不同能力、速度和成本需求。发布当日首先提供 Opus 与 Sonnet，Haiku 随后推出。'),
    event('llama-3', '2024-04-18', 'Llama 3', 'meta', 'weights',
      '8B 与 70B 模型开放权重，继续提升开放模型的通用能力。', ['开放权重', '指令遵循'],
      source('Meta AI · Llama 3 官方公告', 'https://ai.meta.com/blog/meta-llama-3/'), true,
      'Llama 3 首批版本聚焦文本任务，提供预训练和指令微调版本；后续版本继续扩展规模、上下文和模态。'),
    event('deepseek-v2', '2024-05-06', 'DeepSeek-V2', 'deepseek', 'weights',
      '结合混合专家与 MLA 注意力架构，围绕训练和推理效率推进模型设计。', ['MoE', '高效推理'],
      source('DeepSeek · V2 官方仓库发布日志', 'https://github.com/deepseek-ai/DeepSeek-V2'), true,
      'V2 在每个 token 上只激活部分专家参数，并通过多头潜在注意力减少缓存开销。', '按官方仓库 News 中的 2024.05.06 记录。'),
    event('gpt-4o', '2024-05-13', 'GPT-4o', 'openai', 'release',
      '「o」代表 omni。文本、视觉和音频能力走向统一，交互开始更加自然。', ['多模态', '实时交互'], oa('hello-gpt-4o'), true,
      'GPT-4o 采用面向多种模态的端到端模型。不同产品中的语音和视觉功能分阶段开放。'),
    event('qwen-2', '2024-06-07', 'Qwen2', 'qwen', 'weights',
      '覆盖多种参数规模，提升多语言、代码、数学和长上下文能力。', ['开放权重', '多语言'], qw('qwen2'), false,
      'Qwen2 同时包含稠密模型与混合专家模型，提供不同资源条件下的部署选择。'),
    event('claude-3-5', '2024-06-20', 'Claude 3.5 Sonnet', 'anthropic', 'release',
      '提升编程和视觉理解能力，同期的 Artifacts 让内容生成变成可交互的工作空间。', ['编程', '视觉理解'],
      [source('Claude · API 发布日志（2024-06-20）', 'https://platform.claude.com/docs/en/release-notes/overview#june-20th-2024'), an('claude-3-5-sonnet')], true,
      'Claude 3.5 Sonnet 兼顾能力与响应速度，在代码修改、图表理解等场景中进一步提升实用性。', '采用 API 发布日志的 6 月 20 日；当前官方博客页面标注为 6 月 21 日。'),
    event('llama-3-1', '2024-07-23', 'Llama 3.1', 'meta', 'weights',
      '加入 405B 大型版本，将开放模型拓展到更长上下文、多语言与工具使用。', ['开放权重', '长上下文'],
      source('Meta AI · The Llama 3 Herd of Models', 'https://ai.meta.com/research/publications/the-llama-3-herd-of-models'), true,
      '这一代模型包含 8B、70B 和 405B 版本，提供预训练及后训练权重，并在专用许可下开放使用。'),
    event('o1-preview', '2024-09-12', 'OpenAI o1-preview', 'openai', 'preview',
      '在给出答案前花更多时间思考，推理时计算成为新的能力增长方向。', ['推理模型', '数学与代码'], oa('introducing-openai-o1-preview'), true,
      'o1-preview 与 o1-mini 首次公开。模型通过强化学习训练更长的推理过程，面向科学、数学和编程问题。', '记录 o1 预览版发布；不是 12 月正式版发布。'),
    event('qwen-2-5', '2024-09-19', 'Qwen2.5', 'qwen', 'weights',
      '通用、代码与数学模型共同迭代，进一步改善知识、指令遵循和结构化输出。', ['开放权重', '代码与数学'], qw('qwen2.5'), false,
      'Qwen2.5 家族覆盖多种参数规模，并为编码和数学任务提供专门系列。各型号许可并不完全相同。'),
    event('gemini-2', '2024-12-11', 'Gemini 2.0 Flash', 'google', 'preview',
      '发布实验版本，将多模态能力与原生工具使用结合，面向智能体场景。', ['多模态', '工具使用'],
      source('Google · Gemini 2.0 发布公告', 'https://blog.google/innovation-and-ai/models-and-research/google-deepmind/google-gemini-ai-update-december-2024/'), true,
      'Gemini 2.0 Flash 以实验版本首先推出。原生图像生成和语音输出等能力当时仅向部分测试者开放。'),
    event('deepseek-v3', '2024-12-26', 'DeepSeek-V3', 'deepseek', 'weights',
      '671B 参数的混合专家模型开放权重，以每次激活部分参数提高计算效率。', ['MoE', '开放权重'], ds('news1226'), true,
      'DeepSeek-V3 每个 token 激活约 37B 参数，推动大规模混合专家架构在开放模型中的应用。'),
    event('deepseek-r1', '2025-01-20', 'DeepSeek-R1', 'deepseek', 'weights',
      '发布推理模型与多个蒸馏版本，并提供可下载的模型权重。', ['推理模型', '开放权重'], ds('news250120'), true,
      'R1 将强化学习用于推理能力训练，同时发布多个较小的蒸馏模型。代码与 R1 模型采用 MIT 许可，蒸馏版本还需注意其基础模型许可。'),
    event('grok-3', '2025-02-19', 'Grok 3 Beta', 'xai', 'announcement',
      'xAI 发布技术介绍，将思考能力与 DeepSearch 等搜索体验结合。', ['推理', '搜索'],
      source('xAI · Grok 3 Beta 技术公告', 'https://x.ai/news/grok-3'), false,
      '官方技术文章介绍 Grok 3 系列与推理、搜索功能的结合。', '本节点采用官方技术文章标注的 2 月 19 日，不作为直播首发日期。'),
    event('claude-3-7', '2025-02-24', 'Claude 3.7 Sonnet', 'anthropic', 'release',
      '在同一模型中结合快速回答与延伸思考，并同步预览 Claude Code。', ['混合推理', '编程'], an('claude-3-7-sonnet'), true,
      '用户可以选择普通响应或延伸思考模式，开发者也可以控制思考预算。Claude Code 是同期推出的工具产品。'),
    event('gpt-4-5', '2025-02-27', 'GPT-4.5', 'openai', 'preview',
      '继续探索预训练规模带来的收益，强调知识、自然对话与创造性任务。', ['预训练', '自然对话'], oa('introducing-gpt-4-5'), false,
      'GPT-4.5 以研究预览形式推出，与在回答前延长思考的 o 系列代表不同的能力扩展路线。'),
    event('gemini-2-5', '2025-03-25', 'Gemini 2.5 Pro', 'google', 'preview',
      '将思考能力融入模型，推进复杂推理、编程和多模态理解。', ['推理', '多模态'],
      source('Google · Gemini 2.5 发布公告', 'https://blog.google/innovation-and-ai/models-and-research/google-deepmind/gemini-model-thinking-updates-march-2025/'), true,
      'Gemini 2.5 Pro Experimental 是该系列首个发布版本，面向需要多步分析的复杂任务。', '这里记录实验版首次公开日。'),
    event('llama-4', '2025-04-05', 'Llama 4', 'meta', 'weights',
      'Scout 与 Maverick 开放权重，采用混合专家架构并支持原生多模态。', ['MoE', '多模态'],
      source('Meta AI · Llama 4 官方公告', 'https://ai.meta.com/blog/llama-4-multimodal-intelligence/'), true,
      'Llama 4 Scout 和 Maverick 是此次实际推出的模型，公告同时预览更大型的 Behemoth。', '此节点不表示 Behemoth 同日开放。'),
    event('gpt-4-1', '2025-04-14', 'GPT-4.1', 'openai', 'release',
      '面向 API 推出模型家族，着重改善编程、指令遵循与长上下文处理。', ['编程', '长上下文'], oa('gpt-4-1'), false,
      '系列包含 GPT-4.1、mini 和 nano，为不同延迟、成本与能力需求提供选择。', '记录 API 首次发布日。'),
    event('o3-o4-mini', '2025-04-16', 'OpenAI o3 / o4-mini', 'openai', 'release',
      '将推理与工具调用连接起来，模型可以在思考过程中使用搜索、代码和图像。', ['推理', '工具使用'], oa('introducing-o3-and-o4-mini'), true,
      'o3 和 o4-mini 在 ChatGPT 中可组合使用多种工具，进一步拓展推理模型的任务完成能力。', '此处为正式开放使用节点，不是 o3 的早期预告。'),
    event('qwen-3', '2025-04-29', 'Qwen3', 'qwen', 'weights',
      '在一个模型内切换思考与非思考模式，兼顾复杂推理和日常响应。', ['混合推理', '开放权重'], qw('qwen3'), true,
      'Qwen3 包括稠密与混合专家版本，进一步扩展多语言支持，并围绕工具调用与智能体工作流优化。', '采用 Qwen 官方博客标注的 4 月 29 日。'),
    event('claude-4', '2025-05-22', 'Claude Opus 4 / Sonnet 4', 'anthropic', 'release',
      '强化编程、复杂推理和持续执行任务的能力，Claude Code 同期正式可用。', ['编程', '长任务'], an('claude-4'), true,
      'Opus 4 面向复杂任务，Sonnet 4 兼顾能力和效率；两个型号均提供普通与延伸思考模式。'),
    event('grok-4', '2025-07-09', 'Grok 4', 'xai', 'release',
      '推出新一代推理模型，将工具使用与实时信息接入结合。', ['推理', '工具使用'],
      source('xAI · Grok 4 官方公告', 'https://x.ai/news/grok-4'), false,
      '此次发布包含 Grok 4 与面向高难度任务的 Heavy 版本。'),
    event('kimi-k2', '2025-07-11', 'Kimi K2', 'moonshot', 'weights',
      '月之暗面推出 K2，将编码与工具调用作为智能体能力的重要方向。', ['MoE', '工具使用'],
      [source('Kimi · 官方发布日志', 'https://platform.kimi.ai/blog/posts/changelog'), source('Moonshot AI · Kimi K2 官方仓库', 'https://github.com/MoonshotAI/Kimi-K2')], true,
      'Kimi K2 同时提供可下载权重和在线 API，面向代码、工具使用与多步骤任务。'),
    event('glm-4-5', '2025-07-28', 'GLM-4.5', 'zhipu', 'weights',
      '智谱将推理、编码与智能体能力整合进混合推理模型。', ['混合推理', '开放权重'],
      source('Z.ai · GLM-4.5 官方博客', 'https://z.ai/blog/glm-4.5'), true,
      'GLM-4.5 与更轻量的 GLM-4.5-Air 同时发布，支持思考和非思考两种工作模式。'),
    event('gpt-5', '2025-08-07', 'GPT-5', 'openai', 'release',
      '将快速回答与深入推理组织为统一体验，推进编程和复杂问题解决。', ['推理', '编程'], oa('introducing-gpt-5'), true,
      '在 ChatGPT 中，GPT-5 通过路由机制为不同请求选择合适的处理方式；API 提供相应的开发者模型。'),
    event('deepseek-v3-1', '2025-08-21', 'DeepSeek-V3.1', 'deepseek', 'release',
      '统一思考与非思考模式，并优化代码、搜索和工具调用任务。', ['混合推理', '工具使用'],
      source('DeepSeek · 官方更新日志', 'https://api-docs.deepseek.com/updates/#date-2025-08-21'), false,
      'DeepSeek-V3.1 将两种响应模式集成到同一模型中，继续改善推理效率与智能体任务表现。'),
    event('claude-sonnet-4-5', '2025-09-29', 'Claude Sonnet 4.5', 'anthropic', 'release',
      '进一步强化编程与长任务执行，面向真实软件工程工作流。', ['编程', '智能体'], an('claude-sonnet-4-5'), false,
      '该版本围绕编码、计算机使用与复杂工作任务优化，并与 Claude Code 等产品配合使用。'),
    event('kimi-k2-thinking', '2025-11-06', 'Kimi K2 Thinking', 'moonshot', 'weights',
      '边思考、边使用工具，推进长链路搜索、编码与复杂问题求解。', ['推理', '工具使用'],
      [source('Kimi · K2 Thinking 技术介绍', 'https://www.kimi.com/en/blog/kimi-k2-thinking'), source('Kimi · 官方发布日志', 'https://platform.kimi.ai/blog/posts/changelog')], false,
      'K2 Thinking 将推理与连续工具调用交织，面向需要多轮规划和执行的任务。'),
    event('gemini-3', '2025-11-18', 'Gemini 3 Pro', 'google', 'preview',
      '新一代 Gemini 聚焦推理、多模态理解与智能体开发。', ['推理', '多模态'],
      source('Google · Gemini 3 官方公告', 'https://blog.google/products-and-platforms/products/gemini/gemini-3/'), true,
      'Gemini 3 Pro 在 Gemini 应用及开发者平台推出，并与 Antigravity 开发环境同步亮相。', '记录 Pro 预览版，Deep Think 等能力采用不同开放节奏。'),
    event('deepseek-v3-2', '2025-12-01', 'DeepSeek-V3.2', 'deepseek', 'release',
      '继续迭代思考和非思考模式，同时提供侧重高强度推理的 Speciale 版本。', ['推理', '工具使用'],
      source('DeepSeek · 官方更新日志', 'https://api-docs.deepseek.com/updates/#date-2025-12-01'), false,
      '通用 V3.2 与 Speciale 的服务方式和工具能力不同，应分别理解。', '此节点为正式 V3.2 发布，区别于 9 月的 V3.2-Exp。'),
    event('mistral-3', '2025-12-02', 'Mistral 3', 'mistral', 'weights',
      '发布 Mistral Large 3 和多种小型模型，扩大开放多模态模型选择。', ['开放权重', '多模态'],
      source('Mistral AI · Introducing Mistral 3', 'https://mistral.ai/news/mistral-3/'), false,
      '模型家族包含混合专家架构的 Large 3，以及 3B、8B、14B 等较小规模的稠密模型。'),
    event('gpt-5-2', '2025-12-11', 'GPT-5.2', 'openai', 'release',
      '围绕专业知识工作、长上下文理解、编码和工具使用持续改进。', ['知识工作', '长上下文'], oa('introducing-gpt-5-2'), false,
      'GPT-5.2 聚焦更完整的专业任务处理，包括文档、表格、代码和多步骤分析。'),
    event('kimi-k2-5', '2026-01-27', 'Kimi K2.5', 'moonshot', 'weights',
      '将视觉、编码与智能体协作结合，探索更复杂的多模态任务。', ['多模态', '智能体协作'],
      [source('Kimi · K2.5 技术介绍', 'https://www.kimi.com/en/blog/kimi-k2-5'), source('Kimi · 官方产品发布记录', 'https://www.kimi.com/en/help/agent/agent-overview')], true,
      'K2.5 在视觉与文本混合数据上继续预训练，并引入由模型协调多个智能体处理任务的工作方式。'),
    event('glm-5', '2026-02-12', 'GLM-5', 'zhipu', 'announcement',
      '面向复杂系统工程和长时间智能体任务，继续扩展模型规模与训练。', ['智能体工程', '开放权重'],
      source('Z.ai · GLM-5 官方博客', 'https://z.ai/blog/glm-5'), true,
      'GLM-5 将模型目标从单次代码生成扩展到更复杂的软件与系统工程任务，官方同时提供开放权重。', '使用官方技术博客标注的 2 月 12 日，非其他渠道的提前上线日期。'),
    event('qwen-3-5', '2026-02-15', 'Qwen3.5', 'qwen', 'announcement',
      '原生多模态与智能体能力进一步融合，开放首个大型混合专家版本。', ['多模态', 'MoE'],
      source('Qwen · Qwen3.5 官方博客', 'https://qwen.ai/blog?id=qwen3.5'), true,
      'Qwen3.5 首次公告介绍 Qwen3.5-397B-A17B，推进视觉理解、编码和工具使用的融合。', '按官方英文博客标注的 2026/02/15 记录；不同地区报道日期可能不同。'),
    event('gemini-3-1', '2026-02-19', 'Gemini 3.1 Pro', 'google', 'preview',
      '升级核心推理能力，面向需要深入分析的科学、工程与复杂任务。', ['推理', '多模态'],
      source('Google · Gemini 3.1 Pro 官方公告', 'https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-1-pro/'), false,
      '该版本通过 Gemini 应用及开发者平台逐步提供，继续推进复杂推理与多模态任务。'),
    event('deepseek-v4', '2026-04-24', 'DeepSeek-V4 Preview', 'deepseek', 'preview',
      '推出 Pro 与 Flash 两条路线，支持百万 token 上下文并开放模型权重。', ['长上下文', '开放权重'], ds('news260424'), true,
      'V4 的预览发布聚焦长上下文效率、推理与智能体编程，提供面向不同计算需求的两个型号。', '此处为预览版；V4-Pro 正式版于 8 月另行发布。'),
    event('gemini-3-5-flash', '2026-05-19', 'Gemini 3.5 Flash', 'google', 'release',
      '在 Google I/O 推出，将响应速度与智能体任务能力作为重点。', ['高效推理', '智能体'],
      source('Google · I/O 2026 Gemini 公告', 'https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/'), false,
      'Gemini 3.5 Flash 在 Google 多款产品和 API 中推出，配合新一代智能体交互体验。'),
    event('claude-fable-5', '2026-06-09', 'Claude Fable 5 / Mythos 5', 'anthropic', 'release',
      '推出面向高难度编码和知识工作的模型，两个型号采取不同访问范围。', ['复杂任务', '研究'], an('claude-fable-5-mythos-5'), true,
      'Fable 5 面向更广泛使用，Mythos 5 采用受限访问。该节点记录初次发布，而不表示两者均向所有用户开放。', '官方后续记录了 6 月的访问暂停以及 7 月 1 日恢复；这里保留初次发布日期。'),
    event('gpt-5-6', '2026-07-09', 'GPT-5.6', 'openai', 'release',
      '以 Sol、Terra、Luna 等型号覆盖不同任务，聚焦知识工作、设计与编码。', ['模型家族', '复杂任务'], oa('gpt-5-6'), false,
      '该系列围绕不同计算预算下的能力和效率进行设计，并在 ChatGPT、Codex 与 API 中提供。', '记录正式发布，区别于此前的 Sol 预览公告。'),
    event('grok-4-5', '2026-07-16', 'Grok 4.5', 'xai', 'announcement',
      '官方介绍面向编码、智能体任务和知识工作的新版 Grok。', ['编程', '智能体'],
      source('xAI · Grok 4.5 官方公告', 'https://x.ai/news/grok-4-5'), false,
      '该公告重点介绍真实工程任务和专业知识工作中的模型改进。', '采用当前官方文章标注的 7 月 16 日；不将其等同于媒体报道或提前开放日期。'),
    event('claude-fable-5-1', '2026-09-01', 'Claude Fable 5.1 / Mythos 5.1', 'anthropic', 'release',
      '继续强化编码、知识工作和研究能力，Fable 与 Mythos 保持不同开放范围。', ['复杂任务', '研究'],
      source('Anthropic · Fable 与 Mythos 5.1', 'https://www.anthropic.com/claude-fable-and-mythos-5-1'), false,
      'Fable 5.1 面向一般可用场景，Mythos 5.1 仍主要面向通过审核的合作伙伴。'),
    event('gpt-6-astra', '2026-09-03', 'GPT-6 Astra', 'openai', 'release',
      '将推理、计算机使用和专业工作能力结合，面向更完整的复杂任务。', ['计算机使用', '专业工作'],
      [oa('gpt-6-astra'), source('OpenAI · 发布当日安全概述', 'https://openai.com/index/safety-overview-gpt-6-astra/')], true,
      'GPT-6 Astra 的官方发布介绍聚焦浏览器与计算机操作、软件工程和多步骤专业工作。', '发布日期由 9 月 3 日的官方安全概述交叉确认；模型分阶段开放。'),
    event('deepseek-v4-1-flash', '2026-09-10', 'DeepSeek-V4.1-Flash', 'deepseek', 'release',
      '新架构加入原生视觉理解，同时改进推理效率与智能体任务能力。', ['视觉理解', '高效推理'], ds('news260910'), false,
      '官方介绍这一版本为新架构家族中较小的模型，采用非对称编码器与解码器设计。'),
    event('claude-opus-5-5', '2026-09-22', 'Claude Opus 5.5', 'anthropic', 'release',
      '新一代 Opus 面向复杂知识工作、编程与需要审慎判断的任务。', ['编程', '知识工作'],
      source('Anthropic · Claude Opus 5.5', 'https://www.anthropic.com/claude-opus-5-5'), false,
      'Opus 5.5 是 Claude 5.5 家族首个发布型号，官方重点介绍复杂任务处理与运行效率的改进。'),
    event('gpt-6-sol-luna', '2026-09-22', 'GPT-6 Sol / Luna', 'openai', 'release',
      'GPT-6 系列的两个型号，分别面向不同速度与成本需求。', ['高效模型', '知识工作'],
      [oa('introducing-gpt-6-sol-and-luna'), oa('gpt-6-astra')], false,
      'Sol 与 Luna 延续 Astra 的技术进展，面向不同速度和成本需求，在产品和 API 中提供。', '日期由 GPT-6 Astra 官方页面的 9 月 22 日更新交叉确认。'),
    event('claude-sonnet-5-5', '2026-09-28', 'Claude Sonnet 5.5', 'anthropic', 'release',
      'Claude 5.5 家族的第二个型号，面向编程、文档处理和办公任务。', ['编程', '知识工作'],
      source('Anthropic · Claude Sonnet 5.5', 'https://www.anthropic.com/claude-sonnet-5-5'), false,
      'Sonnet 5.5 是 Claude 5.5 家族的第二个型号，与面向复杂任务的 Opus 形成互补。'),
    // Additional major releases cross-checked against Artificial Analysis and Arena.
    event("gpt-4-turbo", "2023-11-06", "GPT-4 Turbo", "openai", "preview",
      "扩展至 128K 上下文，并以开发者预览推进视觉与工具能力。", ["长上下文","多模态"], source("OpenAI · 官方发布", "https://openai.com/index/new-models-and-developer-products-announced-at-devday/"), false,
      "记录首次 DevDay 预览，区别于之后的正式可用版本。同期产品和开发者工具不各自算作新模型。"),
    event("mixtral-8x7b", "2023-12-11", "Mixtral 8×7B", "mistral", "announcement",
      "Mistral 正式介绍稀疏混合专家模型，推动开放模型的效率与能力。", ["混合专家","开放权重"], source("Mistral · 官方发布", "https://mistral.ai/news/mixtral-of-experts/"), false,
      "采用官方技术文章日期；此前的权重文件分享不与正式公告混用。模型以 Apache 2.0 许可提供。"),
    event("gemma-1", "2024-02-21", "Gemma", "google", "weights",
      "Google 发布轻量开放权重模型，拓展研究者与本地开发者的选择。", ["开放权重","轻量模型"], source("Google · 官方博客", "https://blog.google/innovation-and-ai/technology/developers-tools/gemma-open-models/"), true,
      "首批包括 2B 与 7B。Gemma 使用独立模型许可，不能与 Gemini 的托管 API 型号混为一谈。"),
    event("phi-3", "2024-04-23", "Phi-3", "microsoft", "release",
      "微软推出适合本地部署的小型语言模型，强调数据质量与模型效率。", ["轻量模型","端侧部署"], source("Microsoft · 官方发布", "https://news.microsoft.com/source/features/ai/the-phi-3-small-language-models-with-big-potential/"), false,
      "Phi-3 Mini 首先提供，后续扩展不同规模的型号；小参数模型作为主流模型生态的重要分支收录。"),
    event("gemma-2", "2024-06-27", "Gemma 2", "google", "weights",
      "重设模型架构与推理效率，开放 9B 和 27B 两种规模。", ["开放权重","高效推理"], source("Google · 官方博客", "https://blog.google/innovation-and-ai/technology/developers-tools/google-gemma-2/"), false,
      "采用模型实际向开发者开放的日期，区别于此前的大会预告。使用遵循 Gemma 许可。"),
    event("gpt-4o-mini", "2024-07-18", "GPT-4o mini", "openai", "release",
      "提供成本更低的文本与视觉模型，扩展轻量应用的能力。", ["轻量模型","多模态"], source("OpenAI · 官方发布", "https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/"), false,
      "GPT-4o mini 与 GPT-4o 属于不同型号，因此单独收录，而非作为同一模型的推理配置。"),
    event("mistral-large-2", "2024-07-24", "Mistral Large 2", "mistral", "weights",
      "扩展编程、多语言与长上下文能力，提供大规模模型权重。", ["开放权重","多语言"], source("Mistral · 官方发布", "https://mistral.ai/news/mistral-large-2407/"), false,
      "模型为 123B 参数。权重的研究许可与商业使用条件不同，开放权重不代表无限制商用。"),
    event("llama-3-2", "2024-09-25", "Llama 3.2", "meta", "weights",
      "同时扩展视觉语言模型和适合手机、边缘设备的小型文本模型。", ["开放权重","多模态"], source("Meta · 官方发布", "https://ai.meta.com/blog/llama-3-2-connect-2024-vision-edge-mobile-devices/"), false,
      "1B、3B 文本模型与 11B、90B 视觉模型同日发布，按同一家族节点合并。"),
    event("amazon-nova", "2024-12-03", "Amazon Nova", "amazon", "release",
      "亚马逊发布 Nova 家族，覆盖文本与多模态理解的不同成本档位。", ["多模态","云端模型"], source("AWS · 官方发布", "https://aws.amazon.com/about-aws/whats-new/2024/12/amazon-nova-foundation-models-bedrock/"), false,
      "Micro、Lite、Pro 按同日家族发布合并；以语言和多模态理解模型为主，不单列图像与视频生成产品。"),
    event("o1", "2024-12-05", "OpenAI o1", "openai", "release",
      "o1 正式版随 ChatGPT Pro 上线，加强推理并支持图像理解。", ["推理","视觉理解"], source("OpenAI · 官方发布", "https://openai.com/index/introducing-chatgpt-pro/"), false,
      "正式模型取代此前的 o1-preview；这里采用 ChatGPT 产品中的发布日，API 开放时间另有安排。"),
    event("llama-3-3", "2024-12-06", "Llama 3.3", "meta", "weights",
      "更新 70B 指令模型，提高多语言对话和部署效率。", ["开放权重","多语言"], source("Meta · 官方模型卡", "https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct"), false,
      "采用 Meta 官方模型卡标注的发布日期。这是文本模型，不能因前代支持视觉而推断其也支持图像输入。"),
    event("phi-4", "2024-12-12", "Phi-4", "microsoft", "release",
      "通过合成数据与训练改进，加强小型模型的数学和复杂推理能力。", ["轻量模型","推理"], source("Microsoft · 官方发布", "https://techcommunity.microsoft.com/blog/azure-ai-foundry-blog/introducing-phi-4-microsoft%E2%80%99s-newest-small-language-model-specializing-in-comple/4357090"), false,
      "Phi-4 为 14B 参数模型。这里记录 Azure AI Foundry 的首发公告，后续权重开放不与首发混用。"),
    event("o3-mini", "2025-01-31", "OpenAI o3-mini", "openai", "release",
      "推出面向数学、科学和编程的高效推理模型，支持可调思考力度。", ["推理","轻量模型"], source("OpenAI · 官方发布", "https://openai.com/index/openai-o3-mini/"), false,
      "low、medium、high 为同一模型的推理配置。此日是 ChatGPT 与 API 发布，不用此前的预告日期代替。"),
    event("gemma-3", "2025-03-12", "Gemma 3", "google", "weights",
      "将开放权重家族扩展到图像理解、多语言与更长上下文。", ["开放权重","多模态"], source("Google · 官方博客", "https://blog.google/innovation-and-ai/technology/developers-tools/gemma-3/"), false,
      "多个参数规模按同一家族发布合并；不同规模支持的模态和部署需求有所不同。"),
    event("hunyuan-t1", "2025-03-21", "混元 T1", "tencent", "release",
      "腾讯发布深度推理模型，结合混合架构与强化学习。", ["推理","混合架构"], source("腾讯 · 官方发布", "https://cloud.tencent.com/product/events/detail/6702"), false,
      "T1 基于 Turbo S 的混合 Transformer-Mamba 架构训练，记录腾讯云发布页对应的正式版本。"),
    event("mistral-medium-3", "2025-05-07", "Mistral Medium 3", "mistral", "release",
      "面向企业多模态和编程应用，兼顾能力、成本与部署选择。", ["多模态","企业应用"], source("Mistral · 官方发布", "https://mistral.ai/news/mistral-medium-3/"), false,
      "记录 Medium 3 官方发布，与 Le Chat、企业服务等产品更新区分。"),
    event("deepseek-r1-0528", "2025-05-28", "DeepSeek-R1-0528", "deepseek", "release",
      "更新 R1 的推理能力，改进前端编程并支持结构化输出与工具调用。", ["推理","工具使用"], source("DeepSeek · 官方发布日志", "https://api-docs.deepseek.com/news/news250528/"), false,
      "这是有独立官方发布记录的重大模型更新，与原版 R1 分开收录。"),
    event("minimax-m1", "2025-06-16", "MiniMax-M1", "minimax", "paper",
      "以混合注意力探索高效推理与长上下文，公开 M1 技术研究。", ["混合注意力","推理"], source("原始论文 · arXiv", "https://arxiv.org/abs/2506.13585"), true,
      "采用原始论文首次提交日；MiniMax 随后发布模型与面向长程任务的 Agent 产品。"),
    event("qwen-3-coder", "2025-07-22", "Qwen3-Coder", "qwen", "weights",
      "开放面向智能体编程的混合专家模型，强化工具调用与长程任务。", ["开放权重","编程"], source("Qwen · 官方发布", "https://qwenlm.github.io/blog/qwen3-coder/"), false,
      "首发重点型号为 480B-A35B-Instruct；同期 Qwen Code 是开发工具，不作为独立模型节点。"),
    event("claude-opus-4-1", "2025-08-05", "Claude Opus 4.1", "anthropic", "release",
      "改进编程、真实任务中的推理与智能体表现。", ["编程","智能体"], source("Anthropic · 官方发布", "https://www.anthropic.com/news/claude-opus-4-1"), false,
      "作为 Opus 4 的后续独立模型版本收录，连接 Claude 4 与 Opus 4.5 的演进。"),
    event("gpt-oss", "2025-08-05", "gpt-oss-120b / 20b", "openai", "weights",
      "OpenAI 开放两种规模的推理模型权重，支持本地部署与工具使用。", ["开放权重","推理"], source("OpenAI · 官方发布", "https://openai.com/index/introducing-gpt-oss/"), true,
      "120b 与 20b 同日以 Apache 2.0 许可发布，按一次模型家族发布记录。"),
    event("qwen-3-next", "2025-09-10", "Qwen3-Next", "qwen", "announcement",
      "采用混合注意力和高稀疏度设计，探索更高效的长上下文推理。", ["混合注意力","高效推理"], source("Qwen · 官方发布", "https://qwen.ai/blog?from=res&id=4074cca80393150c248e508aa62983f9cb7d27cd"), false,
      "采用官方博客 9 月 10 日公告日期；官方仓库新闻另记录 9 月 11 日模型发布。", "采用官方博客 9 月 10 日公告；官方仓库新闻记录 9 月 11 日发布。"),
    event("glm-4-6", "2025-09-30", "GLM-4.6", "zhipu", "release",
      "升级代码、推理与工具调用能力。", ["编程","智能体"], source("Z.ai · 官方发布日志", "https://docs.z.ai/release-notes/new-released"), false,
      "日期采用 Z.ai 官方平台发布日志。"),
    event("claude-haiku-4-5", "2025-10-15", "Claude Haiku 4.5", "anthropic", "release",
      "面向低延迟场景的小型模型，加强编程与计算机操作能力。", ["轻量模型","编程"], source("Anthropic · 官方发布", "https://www.anthropic.com/news/claude-haiku-4-5"), false,
      "Haiku 系列作为与 Sonnet、Opus 不同的速度和成本档位单独收录。"),
    event("minimax-m2", "2025-10-27", "MiniMax-M2", "minimax", "weights",
      "开放面向编程与智能体的模型，重点优化工具调用和长链任务。", ["开放权重","编程"], source("MiniMax · 官方发布", "https://www.minimax.io/news/minimax-m2"), false,
      "模型与 Agent 产品同步更新；该节点记录 M2 权重和官方模型公告。"),
    event("gpt-5-1", "2025-11-12", "GPT-5.1", "openai", "release",
      "更新 Instant 与 Thinking，改善指令遵循、回答风格与自适应推理。", ["推理","指令遵循"], source("OpenAI · 官方发布", "https://openai.com/index/gpt-5-1/"), false,
      "采用 ChatGPT 首发公告 11 月 12 日；开发者 API 的介绍文章为次日。两个同日型号合并记录。"),
    event("claude-opus-4-5", "2025-11-24", "Claude Opus 4.5", "anthropic", "release",
      "强化编程、计算机操作和长程任务，扩展 Opus 的日常工作能力。", ["编程","工具使用"], source("Anthropic · 官方发布", "https://www.anthropic.com/news/claude-opus-4-5"), false,
      "模型在 Claude 产品、API 和云平台提供。模型标识中的 20251101 是快照名，正式发布公告日期为 11 月 24 日。", "日期为官方首发公告日 2025-11-24，不是模型标识中的快照日期 20251101。"),
    event("nova-2-lite", "2025-12-02", "Amazon Nova 2 Lite", "amazon", "release",
      "引入可调节的扩展思考，面向日常推理、代码和智能体任务。", ["推理","智能体"], source("AWS · 官方发布", "https://aws.amazon.com/blogs/aws/introducing-amazon-nova-2-lite-a-fast-cost-effective-reasoning-model/"), false,
      "Nova 2 Lite 通过 Amazon Bedrock 提供；同一模型的思考预算属于配置，不重复计为发布。"),
    event("nemotron-3-nano", "2025-12-15", "Nemotron 3 Nano", "nvidia", "weights",
      "NVIDIA 发布 Nemotron 3 家族，并率先开放 Nano 模型。", ["开放权重","智能体"], source("NVIDIA · 官方发布", "https://nvidianews.nvidia.com/news/nvidia-debuts-nemotron-3-family-of-open-models"), false,
      "家族包含 Nano、Super、Ultra。此日可获取的是 Nano，后两者的路线公告不等于权重已同时开放。"),
    event("mimo-v2-flash", "2025-12-16", "MiMo-V2-Flash", "xiaomi", "weights",
      "小米开放面向推理、编程与智能体任务的高效语言模型。", ["开放权重","高效推理"], source("小米 MiMo · 官方发布", "https://mimo.xiaomi.com/blog"), false,
      "官方模型日志和发布博客共同记载 12 月 16 日发布。"),
    event("gemini-3-flash", "2025-12-17", "Gemini 3 Flash", "google", "release",
      "将 Gemini 3 的推理能力扩展到更快、更高效的 Flash 档位。", ["多模态","高效推理"], source("Google · 官方博客", "https://blog.google/products-and-platforms/products/gemini/gemini-3-flash/"), false,
      "Flash 是独立型号，按首次官方发布单独收录；不同平台接入日期不再新增节点。"),
    event("glm-4-7", "2025-12-22", "GLM-4.7", "zhipu", "release",
      "增强编程与长上下文中的任务执行。", ["编程","长上下文"], source("Z.ai · 官方发布日志", "https://docs.z.ai/release-notes/new-released"), false,
      "记录 GLM-4.7 正式发布，轻量 Flash 版另计。"),
    event("minimax-m2-1", "2025-12-23", "MiniMax-M2.1", "minimax", "release",
      "加强多种编程语言、办公场景与真实复杂任务中的能力。", ["编程","知识工作"], source("MiniMax · 官方发布", "https://www.minimax.io/blog/minimax-m21"), false,
      "采用 M2.1 首发博客日期，区别于次年 1 月的后续技术解读。"),
    event("glm-4-7-flash", "2026-01-19", "GLM-4.7-Flash", "zhipu", "release",
      "补充 GLM-4.7 系列的轻量版本。", ["轻量模型","编程"], source("Z.ai · 官方发布日志", "https://docs.z.ai/release-notes/new-released"), false,
      "采用官方日志，按独立型号收录。"),
    event("step-3-5-flash", "2026-02-02", "Step 3.5 Flash", "stepfun", "weights",
      "以稀疏混合专家架构兼顾推理速度与智能体能力。", ["开放权重","高效推理"], source("阶跃星辰 · 官方仓库", "https://github.com/stepfun-ai/StepDeepResearch"), false,
      "官方仓库新闻记录 2 月 2 日发布；模型博客后续更新于 2 月 12 日，不用更新日替代首发日。", "官方仓库新闻记载 2 月 2 日首发；模型博客的 2 月 12 日是后续更新日期。"),
    event("claude-opus-4-6", "2026-02-05", "Claude Opus 4.6", "anthropic", "release",
      "加强复杂代码库分析与长程智能体任务，预览百万 token 上下文。", ["长上下文","智能体"], source("Anthropic · 官方发布", "https://www.anthropic.com/news/claude-opus-4-6"), false,
      "此次更新引入自适应思考和推理力度控制，面向编程、研究和文档工作。"),
    event("gpt-5-3-codex", "2026-02-05", "GPT-5.3-Codex", "openai", "release",
      "将编程和通用推理进一步结合，处理研究、工具调用与复杂执行任务。", ["编程","智能体"], source("OpenAI · 官方发布", "https://openai.com/index/introducing-gpt-5-3-codex/"), false,
      "记录新模型在 Codex 中的发布，区别于早期 Codex 产品及 GPT-5.2-Codex。"),
    event("gpt-5-3-codex-spark", "2026-02-12", "GPT-5.3-Codex-Spark", "openai", "preview",
      "面向快速交互编程的小型模型，以研究预览形式提供。", ["编程","低延迟"], source("OpenAI · 官方发布", "https://openai.com/index/introducing-gpt-5-3-codex-spark/"), false,
      "最初向 ChatGPT Pro 用户提供研究预览，使用 Cerebras 推理硬件；不是全面开放的通用 API 发布。"),
    event("minimax-m2-5", "2026-02-12", "MiniMax-M2.5", "minimax", "release",
      "围绕实际编程、搜索、办公与工具调用任务加强强化学习。", ["编程","工具使用"], source("MiniMax · 官方发布", "https://www.minimax.io/news/minimax-m25"), false,
      "M2.5 着重改进真实环境中的多步骤执行与推理效率。"),
    event("seed-2", "2026-02-14", "Seed 2.0", "bytedance", "release",
      "字节跳动发布 Seed 2.0 系列，面向多模态理解与真实世界任务。", ["多模态","智能体"], source("ByteDance Seed · 官方发布", "https://seed.bytedance.com/en/blog/seed-2-0-official-launch"), true,
      "Pro、Lite、Mini 按同日家族发布合并。榜单上使用的测试别名及之后的收录日期不改变首发日。"),
    event("claude-sonnet-4-6", "2026-02-17", "Claude Sonnet 4.6", "anthropic", "release",
      "升级编程、视觉交互、规划与知识工作，扩展 Sonnet 的上下文能力。", ["编程","计算机操作"], source("Anthropic · 官方发布", "https://www.anthropic.com/news/claude-sonnet-4-6"), false,
      "该版本同时面向 Claude 产品与开发者 API，百万 token 上下文以测试形式提供。"),
    event("gpt-5-4", "2026-03-05", "GPT-5.4", "openai", "release",
      "融合推理、编程与原生计算机操作，面向复杂专业工作。", ["计算机操作","长上下文"], source("OpenAI · 官方发布", "https://openai.com/index/introducing-gpt-5-4/"), false,
      "GPT-5.4 与 GPT-5.4 Pro 同日发布，覆盖 ChatGPT、API 和 Codex；同日版本合并记录。"),
    event("nemotron-3-super", "2026-03-11", "Nemotron 3 Super", "nvidia", "weights",
      "采用混合专家架构与长上下文，面向多智能体协作和复杂任务。", ["开放权重","长上下文"], source("NVIDIA · 官方发布", "https://blogs.nvidia.com/blog/nemotron-3-super-agentic-ai/"), false,
      "Super 为 120B 总参数、约 12B 激活参数模型，扩展 Nemotron 3 家族的能力与部署选择。"),
    event("mistral-small-4", "2026-03-16", "Mistral Small 4", "mistral", "weights",
      "在同一模型中整合推理、视觉和编程，并允许调节思考力度。", ["开放权重","多模态"], source("Mistral · 官方发布", "https://mistral.ai/news/mistral-small-4/"), false,
      "以 Apache 2.0 许可提供。不同推理力度不拆分为多个时间线节点。"),
    event("mimo-v2-pro", "2026-03-18", "MiMo-V2-Pro / Omni", "xiaomi", "release",
      "MiMo 家族扩展旗舰推理和全模态能力。", ["推理","多模态"], source("小米 MiMo · 官方发布", "https://mimo.mi.com/docs/en-US/updates/model"), false,
      "同日的 Pro 与 Omni 按家族发布合并；不将仅语音生成的 TTS 另计为通用大模型。"),
    event("minimax-m2-7", "2026-03-18", "MiniMax-M2.7", "minimax", "release",
      "增强软件工程、专业工作与多智能体协作，探索模型参与自身迭代。", ["软件工程","智能体"], source("MiniMax · 官方发布", "https://www.minimax.io/blog/minimax-m27"), false,
      "记录 M2.7 模型首发，后续权重、服务或价格更新不重复计为新模型。"),
    event("gemma-4", "2026-04-02", "Gemma 4", "google", "weights",
      "升级开放模型的推理与智能体能力，并采用 Apache 2.0 许可。", ["开放权重","智能体"], source("Google · 官方博客", "https://blog.google/innovation-and-ai/technology/developers-tools/gemma-4/"), false,
      "记录 Gemma 4 家族首发，后续尺寸与设备适配版本不在这里逐一展开。"),
    event("glm-5-1", "2026-04-07", "GLM-5.1", "zhipu", "release",
      "改进长程软件工程与规划执行。", ["软件工程","智能体"], source("Z.ai · 官方发布日志", "https://docs.z.ai/release-notes/new-released"), false,
      "日期采用 Z.ai 官方平台发布日志。"),
    event("muse-spark", "2026-04-08", "Muse Spark", "meta", "release",
      "Meta 推出 Muse 家族首个模型，结合原生多模态、推理与工具使用。", ["多模态","推理"], source("Meta · 官方发布", "https://ai.meta.com/blog/introducing-muse-spark-msl/"), true,
      "Muse Spark 首先用于 Meta AI 产品，代表 Meta 在 Llama 系列之外的新模型路线。"),
    event("claude-opus-4-7", "2026-04-16", "Claude Opus 4.7", "anthropic", "release",
      "改善高难度软件工程与视觉理解，加强长任务中的自我检查。", ["软件工程","视觉理解"], source("Anthropic · 官方发布", "https://www.anthropic.com/news/claude-opus-4-7"), false,
      "Opus 4.7 是正式可用的 Opus 更新，记录模型发布而非同期其他研究预览。"),
    event("qwen-3-6-max-preview", "2026-04-18", "Qwen3.6-Max Preview", "qwen", "preview",
      "旗舰预览版本加强编程与复杂任务执行。", ["预览模型","智能体"], source("Qwen · 官方发布", "https://qwen.ai/blog?id=qwen3.6-max-preview"), false,
      "保留官方 Preview 名称与发布类型，不将其等同于后续稳定版本。"),
    event("gpt-5-5", "2026-04-23", "GPT-5.5", "openai", "release",
      "增强跨软件、跨工具的任务完成能力，围绕编程和知识工作迭代。", ["智能体","知识工作"], source("OpenAI · 官方发布", "https://openai.com/index/introducing-gpt-5-5/"), false,
      "采用 4 月 23 日产品首发公告；GPT-5.5 与 Pro 的 API 开放为次日 4 月 24 日。", "ChatGPT 与 Codex 首发为 4 月 23 日，API 开放为 4 月 24 日。"),
    event("mimo-v2-5", "2026-04-23", "MiMo-V2.5 / Pro", "xiaomi", "release",
      "升级复杂任务处理，兼顾智能体能力与推理效率。", ["智能体","多模态"], source("小米 MiMo · 官方发布", "https://mimo.mi.com/docs/en-US/updates/model"), false,
      "采用官方模型日志中两种型号同日发布的日期，区别于后续权重开放。"),
    event("qwen-3-7-max", "2026-05-20", "Qwen3.7-Max", "qwen", "release",
      "继续升级智能体编程、办公任务与长程执行能力。", ["编程","知识工作"], source("Qwen · 官方发布", "https://qwen.ai/blog?id=qwen3.7&locale=en"), false,
      "采用官方 Qwen3.7 发布文章日期，连接 Qwen3.6 与 Qwen3.8 系列。"),
    event("mistral-medium-3-5", "2026-05-22", "Mistral Medium 3.5", "mistral", "preview",
      "推出面向长程编程和远程智能体任务的模型公开预览。", ["编程","智能体"], source("Mistral · 官方发布", "https://mistral.ai/news/vibe-remote-agents-mistral-medium-3-5/"), false,
      "128B 模型与 Vibe 远程智能体一起介绍，以公开预览和开放权重形式提供。"),
    event("claude-opus-4-8", "2026-05-28", "Claude Opus 4.8", "anthropic", "release",
      "继续改进工具使用、复杂任务判断和协作体验。", ["智能体","协作"], source("Anthropic · 官方发布", "https://www.anthropic.com/news/claude-opus-4-8"), false,
      "在 Opus 4.7 基础上迭代，并与 Claude Code 的长程工作流程更新同步推出。"),
    event("step-3-7-flash", "2026-05-29", "Step 3.7 Flash", "stepfun", "release",
      "继续增强高效推理和真实任务中的智能体执行能力。", ["高效推理","智能体"], source("阶跃星辰 · 官方发布", "https://static.stepfun.com/blog/step-3.7-flash/"), false,
      "记录官方模型发布文章，而非推理平台后续接入日期。"),
    event("minimax-m3", "2026-06-01", "MiniMax-M3", "minimax", "weights",
      "引入稀疏注意力与原生图像、视频理解，扩展长上下文任务。", ["多模态","长上下文"], source("MiniMax · 官方发布", "https://www.minimax.io/blog/minimax-m3"), false,
      "MiniMax Sparse Attention 与原生多模态结合，面向软件工程和知识工作；使用条件以模型许可为准。"),
    event("kimi-k2-7-code", "2026-06-12", "Kimi K2.7 Code", "moonshot", "release",
      "专注长程编程、工具调用与更高效的思考。", ["编程","工具使用"], source("Kimi · 官方发布日志", "https://www.kimi.com/code/docs/en/kimi-code/whats-new.html"), false,
      "采用官方 Kimi Code 日志的模型发布时间，区别于客户端版本更新。"),
    event("glm-5-2", "2026-06-16", "GLM-5.2", "zhipu", "release",
      "继续增强长程任务与模型工程能力。", ["智能体","长上下文"], source("Z.ai · 官方发布日志", "https://docs.z.ai/release-notes/new-released"), false,
      "采用官方平台日志日期，与第三方平台上架日区分。"),
    event("claude-sonnet-5", "2026-06-30", "Claude Sonnet 5", "anthropic", "release",
      "让 Sonnet 更完整地规划任务、使用浏览器和终端，并持续执行。", ["智能体","工具使用"], source("Anthropic · 官方发布", "https://www.anthropic.com/news/claude-sonnet-5"), false,
      "面向编程和知识工作；不同推理力度属于同一模型配置，不重复记为独立发布。"),
    event("hunyuan-hy3", "2026-07-06", "混元 Hy3", "tencent", "release",
      "升级长程智能体任务与工具使用，并融入腾讯产品生态。", ["智能体","长上下文"], source("腾讯 · 官方发布", "https://www.tencent.com/tencent-hunyuan-officially-releases-hy3-advancing-agent-capabilities-and-deeper-product-integration/"), false,
      "采用腾讯官方英文发布文章日期；该节点记录 Hy3 正式版，区别于此前的预览版。"),
    event("muse-spark-1-1", "2026-07-09", "Muse Spark 1.1", "meta", "announcement",
      "加强编程、计算机操作和多模态理解，并配合 Meta Model API 预览。", ["多模态","工具使用"], source("Meta · 官方发布", "https://ai.meta.com/blog/introducing-muse-spark-meta-model-api/"), false,
      "使用 Meta AI 博客 7 月 9 日的模型公告日期；开发者平台另有 7 月 8 日的 API 文章。", "采用 Meta AI 模型公告 7 月 9 日，开发者 API 文章发表于 7 月 8 日。"),
    event("kimi-k3", "2026-07-16", "Kimi K3", "moonshot", "release",
      "结合原生视觉、长上下文与复杂编程，推进 Kimi 旗舰模型能力。", ["多模态","长上下文"], source("Kimi · 官方发布日志", "https://www.kimi.com/code/docs/en/kimi-code/whats-new.html"), false,
      "采用 Kimi Code 官方日志 7 月 16 日的模型发布记录；完整权重后续于 7 月开放。"),
    event("gemini-3-6-flash", "2026-07-21", "Gemini 3.6 Flash / 3.5 Flash-Lite", "google", "release",
      "Flash 系列继续提升推理效率，并补充更轻量的 Flash-Lite。", ["多模态","高效推理"], source("Google · 官方博客", "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-6-flash-3-5-flash-lite-3-5-flash-cyber/"), false,
      "同日发布 3.6 Flash、3.5 Flash-Lite，并介绍用于受限安全场景的 3.5 Flash Cyber；按一次家族公告合并记录。"),
    event("claude-opus-5", "2026-07-24", "Claude Opus 5", "anthropic", "release",
      "升级软件工程、知识工作与计算机操作，强化复杂任务的执行能力。", ["软件工程","知识工作"], source("Anthropic · 官方发布", "https://www.anthropic.com/news/claude-opus-5"), false,
      "记录 Opus 5 首次正式发布，与此前的 Fable 5 及后续 Opus 5.5 分开。"),
    event("qwen-3-8-max", "2026-08-03", "Qwen3.8-Max", "qwen", "release",
      "推出新一代多模态旗舰，支持长上下文和复杂智能体任务。", ["多模态","智能体"], source("Qwen · 官方发布", "https://docs.qwencloud.com/changelog/models"), false,
      "记录 QwenCloud 官方模型日志中的首次发布；9 月快照更新另行记录。"),
    event("grok-4-6", "2026-08-12", "Grok 4.6", "xai", "announcement",
      "加强长程智能体、互动应用和视觉工作中的持续执行能力。", ["智能体","视觉理解"], source("xAI · 官方发布", "https://x.ai/news/grok-4-6"), false,
      "采用官方技术文章 8 月 12 日的日期；API 发布日志另记 8 月 11 日开放。", "采用官方技术公告 8 月 12 日；API 日志记录 8 月 11 日开放。"),
    event("qwen-3-8", "2026-08-12", "Qwen3.8 开放权重系列", "qwen", "weights",
      "开放 2.4T-A95B 模型，并随后补充 27B 版本。", ["开放权重","多模态"], source("Qwen · 模型仓库", "https://github.com/QwenLM/Qwen3.8"), false,
      "官方仓库记录 2.4T-A95B 于 8 月 12 日开放，27B 于 8 月 14 日开放；家族首个节点采用前者。", "首批 2.4T-A95B 权重于 8 月 12 日开放；27B 权重于 8 月 14 日开放。"),
    event("deepseek-v4-pro-0813", "2026-08-13", "DeepSeek-V4-Pro 正式版", "deepseek", "release",
      "V4 Pro 转为正式版本，强化智能体任务并原生支持 Responses API。", ["智能体","工具使用"], source("DeepSeek · 官方发布日志", "https://api-docs.deepseek.com/zh-cn/news/news260813/"), false,
      "采用官方发布日志 8 月 13 日；0813 为此次模型快照，与 4 月的 V4 预览分开。"),
    event("gemini-3-7-flash", "2026-08-13", "Gemini 3.7 Flash", "google", "release",
      "继续增强编程、知识工作与网页开发中的多步骤任务处理。", ["编程","智能体"], source("Google · 官方博客", "https://blog.google/innovation-and-ai/models-and-research/gemini-models/introducing-gemini-3-7-flash/"), false,
      "这是 Flash 系列在 3.6 之后的模型迭代，开发者、企业和消费者端分渠道提供。"),
    event("glm-5-3", "2026-08-18", "GLM-5.3", "zhipu", "release",
      "强化复杂编程与长期任务执行。", ["编程","智能体"], source("Z.ai · 官方发布日志", "https://docs.z.ai/release-notes/new-released"), false,
      "采用官方平台 8 月 18 日发布日志，不以早期订阅预览日期代替。", "采用官方平台 8 月 18 日发布日志；早期订阅预览与平台正式发布口径不同。"),
    event("glm-5-3-flash", "2026-08-26", "GLM-5.3-Flash", "zhipu", "release",
      "GLM 系列补充新的 Flash 模型。", ["高效推理","智能体"], source("Z.ai · 官方发布日志", "https://docs.z.ai/release-notes/new-released"), false,
      "日期采用官方平台发布日志。"),
    event("qwen-3-8-flash", "2026-08-26", "Qwen3.8-Flash", "qwen", "release",
      "面向高并发多模态应用，兼顾长上下文、编程与智能体处理。", ["多模态","高效推理"], source("Qwen · 官方发布", "https://docs.qwencloud.com/changelog/models"), false,
      "采用 QwenCloud 官方日志的 8 月 26 日发布记录。"),
    event("hunyuan-hy4-preview", "2026-08-28", "混元 Hy4 Preview", "tencent", "preview",
      "开放新一代旗舰预览模型，扩展长上下文与复杂工作任务能力。", ["开放权重","智能体"], source("腾讯 · 官方发布", "https://www.tencent.com/tencent-releases-and-open-sources-tencent-hy4-preview/"), false,
      "模型以 Preview 名称发布并提供权重和 API；保持预览类型，不将其标成正式版。"),
    event("gemini-3-8-flash", "2026-09-02", "Gemini 3.8 Flash", "google", "release",
      "提升长程编程与专业推理，同期发布受限提供的 Cyber 版本。", ["推理","智能体"], source("Google · 官方博客", "https://blog.google/innovation-and-ai/models-and-research/gemini-models/3-8-flash-and-3-8-flash-cyber/"), false,
      "Flash 面向常规开发与产品使用；Flash Cyber 通过特定计划向获准用户提供，不能理解为全量开放。"),
    event("muse-spark-1-3", "2026-09-02", "Muse Spark 1.3", "meta", "release",
      "改善长程智能体任务与编程，增强同一会话中的持续协作。", ["智能体","编程"], source("Meta · 官方发布", "https://research.meta.ai/blog/introducing-muse-spark-1-3"), false,
      "通过 Muse Code 和 Meta Model API 提供；max 等推理配置合并到这一发布节点。"),
    event("qwen-3-8-max-0902", "2026-09-02", "Qwen3.8-Max-0902", "qwen", "release",
      "更新旗舰快照，强化工程项目、工具协作和视觉理解。", ["编程","视觉理解"], source("Qwen · 官方发布", "https://docs.qwencloud.com/changelog/model-updates/qwen3.8-max-upgrade"), false,
      "9 月 2 日快照先行可用；默认 qwen3.8-max 端点于 9 月 5 日切换，二者日期区分。", "9 月 2 日快照可用，9 月 5 日默认端点切换；不以端点切换日代替模型发布日。"),
    event("kimi-k2-8-preview", "2026-09-11", "Kimi K2.8 Preview", "moonshot", "preview",
      "升级 Kimi Code 中的编程与智能体能力，支持长上下文。", ["编程","预览模型"], source("Kimi · 官方发布日志", "https://www.kimi.com/code/docs/en/kimi-code/whats-new.html"), false,
      "节点对应该预览模型在 Kimi Code 的全量推出，不等于独立权重已开放。"),
    event("qwen-3-8-omni-flash", "2026-09-18", "Qwen3.8-Omni-Flash", "qwen", "release",
      "统一处理文本、图像、音频和视频，扩展多模态工作流程。", ["全模态","工具使用"], source("Qwen · 官方发布", "https://docs.qwencloud.com/changelog/models"), false,
      "记录 Omni 模型发布；9 月 21 日的 Realtime 接口是后续实时交互扩展。"),
    event("step-5-preview", "2026-09-20", "Step 5 Preview", "stepfun", "preview",
      "面向长程软件工程、知识工作与金融研究的旗舰预览模型。", ["多模态","智能体"], [source("阶跃星辰 · 官方发布", "https://www.stepfun.com/step-5-preview"), source("IT之家 · 首发日期交叉核验", "https://www.ithome.com/1/004/705.htm")], false,
      "发布时提供预览与 API，完整权重当时计划于 10 月开放，不能视为发布日已经开放权重。", "预览与 API 于 9 月 20 日发布，日期由首发报道交叉核验。发布时完整权重计划于 10 月 15 日开放，该计划不作为已经发生的事件。"),
    event("grok-4-7", "2026-09-21", "Grok 4.7", "xai", "release",
      "升级编程和知识工作，改善复杂任务的自我验证与上下文管理。", ["编程","知识工作"], source("xAI · 官方发布", "https://x.ai/news/grok-4-7"), false,
      "不同推理档位与加速服务归入同一模型发布，不按榜单中的配置重复计数。"),
    event("mimo-v2-6", "2026-09-22", "MiMo-V2.6 Pro / Flash", "xiaomi", "release",
      "结合全模态理解与大规模强化学习，升级长程任务能力。", ["全模态","智能体"], source("小米 MiMo · 官方发布", "https://mimo.mi.com/docs/en-US/updates/model"), false,
      "采用官方模型发布日志 9 月 22 日；Pro 的加速服务不作为新模型重复计数。"),
    {"id": "gpt-6-1-sol", "date": "2026-09-29", "name": "GPT-6.1 Sol", "company": "openai", "kind": "release", "summary": "升级编程、计算机操作与专业任务能力，并支持在单次请求中分派子任务。", "details": "GPT-6.1 Sol 延续 Sol 的价格定位，提供 1,050,000 tokens 上下文和图像输入，改进长程工具使用。Multi-agent 以测试功能提供；推理档位与产品接入方式合并在同一节点记录。", "dateNote": "采用 OpenAI API 更新日志的 9 月 29 日。ChatGPT Work 与 Codex 的分批开放不另作模型发布时间。", "tags": ["推理", "多模态", "智能体"], "milestone": false, "sources": [{"title": "OpenAI · API 发布日志", "url": "https://developers.openai.com/api/docs/changelog"}, {"title": "OpenAI · 模型文档", "url": "https://developers.openai.com/api/docs/models/gpt-6.1-sol"}]},
    {"id": "gemini-4-argon", "date": "2026-09-30", "name": "Gemini 4 Argon", "company": "google", "kind": "announcement", "summary": "面向复杂编程、知识工作与网络防御的新一代多模态模型，先向受邀团队开放。", "details": "Google 公布 Gemini 4 Argon，并通过 Fairwind 计划向受邀网络防御团队逐步开放。模型侧重多步骤推理与长程任务；面向开发者和消费者的普遍开放尚未开始。", "dateNote": "采用 Google 公告标注的 9 月 30 日，记录模型公布与有限开放，不能视为公开 API 或 Gemini 应用全面上线。", "tags": ["多模态", "推理", "智能体"], "milestone": false, "sources": [{"title": "Google · 模型公告", "url": "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-4-argon/"}, {"title": "Google DeepMind · 模型与评测", "url": "https://deepmind.google/models/gemini/"}]},
  ].sort((a, b) => a.date.localeCompare(b.date) || a.id.localeCompare(b.id));
  const coverage = {
    checkedAt: '2026-10-01',
    scope: '主流通用语言、推理、编程模型及其多模态扩展，兼顾重要历史研究与产品节点。',
    method: '参考公开榜单、公告、论文与权威报道，记录证据和核对日期；推理档位与同日家族型号合并收录。',
    criteria: ['具有前沿表现、明确技术代表性或重要历史影响。', '收录首发、主要代际与实质能力更新，合并小版本、推理档位和平台副本。', '必须有可核验的公开日期与可信来源；厂商知名度或出现在榜单上不自动构成收录理由。'],
    references: [
      source('Artificial Analysis · Intelligence', 'https://artificialanalysis.ai/models#intelligence'),
      source('Arena · Text leaderboard', 'https://arena.ai/leaderboard/text'),
      source('LiveBench', 'https://livebench.ai/'),
      source('HELM Capabilities', 'https://crfm.stanford.edu/helm/capabilities/latest/'),
      source('OpenCompass', 'https://rank.opencompass.org.cn/'),
      source('SWE-bench', 'https://www.swebench.com/'),
      source('Terminal-Bench', 'https://www.tbench.ai/'),
    ],
  };
  return Object.freeze({ asOf: '2026-10-01', updatedAt: '2026-10-01', companies, companyRanking, kinds, themes, releases, coverage });
})();
